from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class GeoSpatialNavigationQuery(BaseModel):
    """
    Input query payload for Geo-Spatial & Navigation Intelligence Agent.
    Supports single coordinate assessment and origin-to-destination route evaluation.
    """
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Origin latitude in decimal degrees (-90.0 to 90.0)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Origin longitude in decimal degrees (-180.0 to 180.0)")
    destination_latitude: Optional[float] = Field(None, ge=-90.0, le=90.0, description="Optional destination latitude in decimal degrees (-90.0 to 90.0)")
    destination_longitude: Optional[float] = Field(None, ge=-180.0, le=180.0, description="Optional destination longitude in decimal degrees (-180.0 to 180.0)")


class SpatialEvidenceItem(BaseModel):
    """
    Standardized traceable spatial evidence item with provenance and regulatory attributes.
    """
    factor: str = Field(..., description="Spatial factor identifier (e.g. nearest_port, restricted_zone_containment, route_restricted_intersection)")
    name: Optional[str] = Field(None, description="Name of the spatial entity or zone")
    zone_type: Optional[str] = Field(None, description="Classification type of the zone or entity")
    spatial_relation: str = Field("NEARBY", description="CONTAINS, INTERSECTS, NEARBY, OUTSIDE, ENDPOINT, LINE_TRAJECTORY")
    distance_km: Optional[float] = Field(None, description="Distance from origin or route in kilometers")
    latitude: Optional[float] = Field(None, description="Entity latitude")
    longitude: Optional[float] = Field(None, description="Entity longitude")
    source: str = Field("PostGIS / Spatial Registry", description="Data authority or spatial registry source")
    data_type: str = Field("SPATIAL_REGULATORY", description="SPATIAL_REGULATORY, SPATIAL_INFRASTRUCTURE, SPATIAL_ANALYSIS")
    confidence: float = Field(1.0, ge=0.0, le=1.0, description="Deterministic confidence score between 0.0 and 1.0")
    freshness: str = Field("FRESH", description="Freshness evaluation: FRESH, AGING, STALE, UNKNOWN")
    severity: str = Field("NORMAL", description="Severity status: NORMAL, CAUTION, RESTRICTED, BLOCKED, UNKNOWN")
    notes: Optional[str] = Field(None, description="Diagnostic spatial context note")


class SpatialEntitySummary(BaseModel):
    """
    Structured summary of a nearby or containing spatial entity (port, sanctuary, restricted sector).
    """
    id: Optional[int] = None
    name: str
    entity_type: str = Field(..., description="PORT, RESTRICTED_ZONE, PROTECTED_ZONE")
    zone_type: Optional[str] = None
    distance_km: Optional[float] = None
    distance_nautical_miles: Optional[float] = None
    spatial_relation: str = Field("NEARBY", description="CONTAINS, NEARBY, INTERSECTS")
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    authority: Optional[str] = None
    description: Optional[str] = None


class RouteAssessmentSummary(BaseModel):
    """
    Detailed geometric and regulatory assessment of a proposed navigation route.
    """
    has_destination: bool = Field(False, description="True if destination coordinates were provided")
    status: str = Field("NOT_APPLICABLE", description="CLEAR, CAUTION, RESTRICTED, BLOCKED, NOT_APPLICABLE, INSUFFICIENT_DATA")
    distance_km: Optional[float] = None
    distance_nautical_miles: Optional[float] = None
    origin_in_restricted_zone: bool = False
    destination_in_restricted_zone: bool = False
    origin_in_protected_zone: bool = False
    destination_in_protected_zone: bool = False
    restricted_zone_intersection: bool = False
    protected_zone_intersection: bool = False
    intersecting_restricted_zones: List[str] = Field(default_factory=list)
    intersecting_protected_zones: List[str] = Field(default_factory=list)
    alternative_route_available: bool = False
    alternative_route_suggestion: Optional[str] = None
    reasons: List[str] = Field(default_factory=list)


class DistanceSummary(BaseModel):
    """
    Geodesic distance calculation summary.
    """
    distance_km: Optional[float] = None
    distance_nautical_miles: Optional[float] = None
    calculation_method: str = "HAVERSINE_GEODESIC"


class GeoSpatialNavigationAssessmentResponse(BaseModel):
    """
    Structured response generated by the Geo-Spatial & Navigation Intelligence Agent.
    """
    agent: str = Field("geospatial_navigation", description="Name of the domain agent")
    origin: Dict[str, float] = Field(..., description="Origin coordinates")
    destination: Optional[Dict[str, float]] = Field(None, description="Optional destination coordinates")
    spatial_status: str = Field(..., description="Overall spatial navigation status: CLEAR, CAUTION, RESTRICTED, PROTECTED, BLOCKED, INSUFFICIENT_DATA")
    geofence_status: str = Field("OUTSIDE", description="Geofence containment state: OUTSIDE, NEAR_BOUNDARY, INSIDE_RESTRICTED, INSIDE_PROTECTED")
    nearby_entities: List[SpatialEntitySummary] = Field(default_factory=list, description="Nearest coastal ports and infrastructure")
    zones: List[SpatialEntitySummary] = Field(default_factory=list, description="Containing and nearby restricted/protected maritime zones")
    route: Optional[RouteAssessmentSummary] = Field(None, description="Route spatial intersection and clearance evaluation")
    distance: Optional[DistanceSummary] = Field(None, description="Geodesic distance summary if destination provided")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Deterministic spatial confidence rating")
    data_freshness: str = Field("FRESH", description="Freshness status of spatial registry data")
    evidence: List[SpatialEvidenceItem] = Field(default_factory=list, description="Traceable spatial evidence items")
    warnings: List[str] = Field(default_factory=list, description="List of spatial navigation alerts or boundary warnings")
    recommendation: str = Field(..., description="Actionable spatial navigation guidance")
    explanation: str = Field(..., description="Evidence-based reasoning narrative")
    generated_at: datetime = Field(..., description="UTC timestamp of response generation")

    model_config = ConfigDict(from_attributes=True)
