import React, { createContext, useContext, useState, type ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'te' | 'ta' | 'kn' | 'ml' | 'mr' | 'bn' | 'gu';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🌐' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.maps': 'Live Map',
    'nav.fishing': 'Fishing Intelligence',
    'nav.marine_conditions': 'Marine Conditions',
    'nav.earth_observation': 'Earth Observation',
    'nav.navigation': 'Geo-Spatial & Nav',
    'nav.safety': 'Disaster & Safety',
    'nav.operations': 'Marine Operations',
    'nav.ask': 'Ask OCEANIS',
    'nav.agents': 'Domain Agents',
    'nav.reports': 'Reports',
    'nav.data_sources': 'Data Sources',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.change_loc': 'Change',
    'nav.select_loc': 'Select Location',
    'nav.sector_suffix': 'Sector',
    'nav.offshore_sector': 'Offshore Sector',
    'nav.inland_sector': 'Inland Sector',
    'nav.loc_not_selected': 'Location Not Selected',

    // Dashboard & Overview
    'dash.title': 'Marine Intelligence Dashboard',
    'dash.subtitle': 'Unified multi-agent maritime decision intelligence & operational telemetry',
    'dash.live_map_title': 'Live Ocean Intelligence Map',
    'dash.safety_status': 'Safety Status',
    'dash.trusted_sources': 'Trusted Institutional Data Sources',
    'dash.system_status': 'System Status',
    'dash.active_advisories': 'Operational Advisories',
    'dash.fishing_suitability': 'Fishing Suitability',
    'dash.satellite_eo': 'Satellite Earth Observation',
    'dash.decision_summary': 'Operational Decision Intelligence',
    'dash.what_if': 'What-If Marine Simulation',

    // Ask OCEANIS
    'ask.title': 'Ask OCEANIS',
    'ask.subtitle': 'Natural-language & Voice marine intelligence synthesized across specialized domain agents with deterministic safety verification.',
    'ask.input_placeholder': 'Ask any natural language or voice marine question (English, Telugu, Hindi, Tamil...)',
    'ask.btn_analyze': 'Analyze Query',
    'ask.btn_consulting': 'Consulting Agents...',
    'ask.voice_btn': 'Voice',
    'ask.voice_listening': 'Listening...',
    'ask.voice_banner': 'Listening... Speak your marine question naturally in your chosen language',
    'ask.read_aloud': 'Read Aloud',
    'ask.stop_voice': 'Stop Voice',
    'ask.why_title': 'Why This Decision?',
    'ask.why_sub': 'Multi-domain evidence tracing across environmental and regulatory factors',
    'ask.agents_consulted': 'Agents Consulted',
    'ask.agents_sub': 'Dynamic multi-agent coordination with specialized evidence contributions',
    'ask.evidence_title': 'Structured Evidence & Source Provenance',
    'ask.evidence_sub': 'Real telemetry strictly separated from AI analysis with dynamic freshness tracking',
    'ask.follow_up_label': 'Follow-up Context:',
    'ask.recent_turns': 'Recent Intelligence Turns',
    'ask.confidence': 'Confidence',
    'ask.telemetry': 'Telemetry',

    // Statuses & Badges
    'status.recommended': 'Recommended',
    'status.caution': 'Caution',
    'status.not_recommended': 'Not Recommended',
    'status.insufficient_evidence': 'Insufficient Evidence',
    'status.fresh': 'Fresh',
    'status.aging': 'Aging',
    'status.stale': 'Stale',
    'status.unavailable': 'Unavailable',
    'status.operational': 'Operational',
    'status.synchronized': 'Synchronized',
    'status.clear': 'Clear for Transit',
    'status.warning': 'Warning',
    'status.alert': 'Alert',

    // Disclaimer
    'disclaimer.text': 'Operational Decision Support System — Not a Guarantee of Maritime Safety. Always cross-reference with official local port authorities, Coast Guard, and IMD/INCOIS meteorological bulletins before initiating offshore voyages.',
  },

  te: {
    // Navigation
    'nav.home': 'హోమ్',
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.maps': 'లైవ్ మ్యాప్',
    'nav.fishing': 'చేపల వేట సమాచారం',
    'nav.marine_conditions': 'సముద్ర పరిస్థితులు',
    'nav.earth_observation': 'భూ పరిశీలన (శాటిలైట్)',
    'nav.navigation': 'భౌగోళిక & నావిగేషన్',
    'nav.safety': 'విపత్తు & భద్రత',
    'nav.operations': 'సముద్ర కార్యకలాపాలు',
    'nav.ask': 'OCEANIS ను అడగండి',
    'nav.agents': 'డొమైన్ ఏజెంట్లు',
    'nav.reports': 'నివేదికలు',
    'nav.data_sources': 'డేటా మూలాలు',
    'nav.analytics': 'విశ్లేషణలు',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.change_loc': 'మార్చండి',
    'nav.select_loc': 'ప్రాంతాన్ని ఎంచుకోండి',
    'nav.sector_suffix': 'సెక్టార్',
    'nav.offshore_sector': 'ఆఫ్‌షోర్ సెక్టార్',
    'nav.inland_sector': 'ఇన్‌ల్యాండ్ సెక్టార్',
    'nav.loc_not_selected': 'ప్రాంతం ఎంచుకోలేదు',

    // Dashboard & Overview
    'dash.title': 'సముద్ర సమాచార డ్యాష్‌బోర్డ్',
    'dash.subtitle': 'ఏకీకృత మల్టీ-ఏజెంట్ సముద్ర నిర్ణయ మేధస్సు మరియు కార్యాచరణ టెలిమెట్రీ',
    'dash.live_map_title': 'లైవ్ సముద్ర మేధస్సు మ్యాప్',
    'dash.safety_status': 'భద్రతా స్థితి',
    'dash.trusted_sources': 'విశ్వసనీయ సంస్థాగత డేటా మూలాలు',
    'dash.system_status': 'సిస్టమ్ స్థితి',
    'dash.active_advisories': 'కార్యాచరణ హెచ్చరికలు',
    'dash.fishing_suitability': 'చేపల వేట అనుకూలత',
    'dash.satellite_eo': 'శాటిలైట్ భూ పరిశీలన',
    'dash.decision_summary': 'కార్యాచరణ నిర్ణయ మేధస్సు',
    'dash.what_if': 'సముద్ర వాట్-ఇఫ్ సిమ్యులేషన్',

    // Ask OCEANIS
    'ask.title': 'OCEANIS ను అడగండి',
    'ask.subtitle': 'ప్రత్యేక డొమైన్ ఏజెంట్ల ద్వారా సంశ్లేషణ చేయబడిన సహజ భాష & వాయిస్ సముద్ర మేధస్సు.',
    'ask.input_placeholder': 'ఏదైనా సముద్ర సంబంధిత ప్రశ్నను అడగండి (తెలుగు, English, Hindi...)',
    'ask.btn_analyze': 'విశ్లేషించండి',
    'ask.btn_consulting': 'ఏజెంట్లను సంప్రదిస్తోంది...',
    'ask.voice_btn': 'వాయిస్',
    'ask.voice_listening': 'వింటోంది...',
    'ask.voice_banner': 'వింటోంది... మీ సముద్ర ప్రశ్నను సహజంగా మాట్లాడండి',
    'ask.read_aloud': 'చదివి వినిపించు',
    'ask.stop_voice': 'వాయిస్ ఆపు',
    'ask.why_title': 'ఈ నిర్ణయం ఎందుకు?',
    'ask.why_sub': 'పర్యావరణ మరియు నియంత్రణ అంశాల బహుళ-డొమైన్ సాక్ష్యం',
    'ask.agents_consulted': 'సంప్రదించిన ఏజెంట్లు',
    'ask.agents_sub': 'నిర్దిష్ట ఆధారాలతో డైనమిక్ మల్టీ-ఏజెంట్ సమన్వయం',
    'ask.evidence_title': 'నిర్మాణాత్మక ఆధారాలు & డేటా మూలాలు',
    'ask.evidence_sub': 'AI విశ్లేషణ నుండి వేరు చేయబడిన నిజమైన టెలిమెట్రీ',
    'ask.follow_up_label': 'తదుపరి ప్రశ్నలు:',
    'ask.recent_turns': 'ఇటీవలి సంభాషణలు',
    'ask.confidence': 'విశ్వసనీయత',
    'ask.telemetry': 'టెలిమెట్రీ',

    // Statuses & Badges
    'status.recommended': 'సిఫార్సు చేయబడింది',
    'status.caution': 'జాగ్రత్త అవసరం',
    'status.not_recommended': 'సిఫార్సు చేయబడలేదు',
    'status.insufficient_evidence': 'సరిపోని ఆధారాలు',
    'status.fresh': 'తాజాది (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'అందుబాటులో లేదు',
    'status.operational': 'కార్యాచరణలో ఉంది',
    'status.synchronized': 'సింక్రొనైజ్ చేయబడింది',
    'status.clear': 'ప్రయాణానికి అనుకూలం',
    'status.warning': 'హెచ్చరిక',
    'status.alert': 'అలర్ట్',

    // Disclaimer
    'disclaimer.text': 'నిర్ణయ మద్దతు వ్యవస్థ — సముద్ర భద్రతకు హామీ కాదు. సముద్రంలోకి వెళ్లే ముందు ఎల్లప్పుడూ అధికారిక స్థానిక పోర్ట్ అధికారులు, కోస్ట్ గార్డ్ మరియు IMD / INCOIS బులెటిన్‌లను చూడండి.',
  },

  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.maps': 'लाइव मानचित्र',
    'nav.fishing': 'मत्स्य पालन खुफिया',
    'nav.marine_conditions': 'समुद्री स्थितियाँ',
    'nav.earth_observation': 'पृथ्वी अवलोकन (उपग्रह)',
    'nav.navigation': 'भू-स्थानिक और नेविगेशन',
    'nav.safety': 'आपदा और सुरक्षा',
    'nav.operations': 'समुद्री संचालन',
    'nav.ask': 'OCEANIS से पूछें',
    'nav.agents': 'डोमेन एजेंट',
    'nav.reports': 'रिपोर्ट्स',
    'nav.data_sources': 'डेटा स्रोत',
    'nav.analytics': 'एनालिटिक्स',
    'nav.settings': 'सेटिंग्स',
    'nav.change_loc': 'बदलें',
    'nav.select_loc': 'स्थान चुनें',
    'nav.sector_suffix': 'सेक्टर',
    'nav.offshore_sector': 'ऑफशोर सेक्टर',
    'nav.inland_sector': 'अंतर्देशीय सेक्टर',
    'nav.loc_not_selected': 'स्थान चयनित नहीं है',

    // Dashboard & Overview
    'dash.title': 'समुद्री खुफिया डैशबोर्ड',
    'dash.subtitle': 'एकीकृत मल्टी-एजेंट समुद्री निर्णय खुफिया और परिचालन टेलीमेट्री',
    'dash.live_map_title': 'लाइव महासागर खुफिया मानचित्र',
    'dash.safety_status': 'सुरक्षा स्थिति',
    'dash.trusted_sources': 'विश्वसनीय संस्थागत डेटा स्रोत',
    'dash.system_status': 'सिस्टम स्थिति',
    'dash.active_advisories': 'परिचालन सलाह',
    'dash.fishing_suitability': 'मत्स्य पालन उपयुक्तता',
    'dash.satellite_eo': 'उपग्रह पृथ्वी अवलोकन',
    'dash.decision_summary': 'परिचालन निर्णय खुफिया',
    'dash.what_if': 'व्हाट-इफ़ समुद्री सिमुलेशन',

    // Ask OCEANIS
    'ask.title': 'OCEANIS से पूछें',
    'ask.subtitle': 'विशेषज्ञ डोमेन एजेंटों द्वारा संश्लेषित प्राकृतिक भाषा और वॉयस समुद्री खुफिया।',
    'ask.input_placeholder': 'कोई भी समुद्री प्रश्न पूछें (हिन्दी, English, Telugu, Tamil...)',
    'ask.btn_analyze': 'विश्लेषण करें',
    'ask.btn_consulting': 'एजेंटों से परामर्श ले रहे हैं...',
    'ask.voice_btn': 'वॉयस',
    'ask.voice_listening': 'सुन रहा है...',
    'ask.voice_banner': 'सुन रहा है... अपना समुद्री प्रश्न स्वाभाविक रूप से बोलें',
    'ask.read_aloud': 'बोलकर सुनाएं',
    'ask.stop_voice': 'वॉयस रोकें',
    'ask.why_title': 'यह निर्णय क्यों?',
    'ask.why_sub': 'पर्यावरणीय और नियामक कारकों में बहु-डोमेन साक्ष्य',
    'ask.agents_consulted': 'परामर्शित एजेंट',
    'ask.agents_sub': 'विशिष्ट साक्ष्यों के साथ गतिशील मल्टी-एजेंट समन्वय',
    'ask.evidence_title': 'संरचित साक्ष्य और डेटा स्रोत',
    'ask.evidence_sub': 'AI विश्लेषण से अलग की गई वास्तविक टेलीमेट्री',
    'ask.follow_up_label': 'अनुवर्ती प्रश्न:',
    'ask.recent_turns': 'हाल की बातचीत',
    'ask.confidence': 'विश्वास',
    'ask.telemetry': 'टेलीमेट्री',

    // Statuses & Badges
    'status.recommended': 'अनुशंसित',
    'status.caution': 'सावधानी',
    'status.not_recommended': 'अनुशंसित नहीं',
    'status.insufficient_evidence': 'अपर्याप्त साक्ष्य',
    'status.fresh': 'ताज़ा (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'अनुपलब्ध',
    'status.operational': 'सक्रिय',
    'status.synchronized': 'सिंक्रनाइज़्ड',
    'status.clear': 'यात्रा के लिए स्पष्ट',
    'status.warning': 'चेतावनी',
    'status.alert': 'अलर्ट',

    // Disclaimer
    'disclaimer.text': 'निर्णय समर्थन प्रणाली — समुद्री सुरक्षा की गारंटी नहीं। समुद्र में जाने से पहले हमेशा आधिकारिक स्थानीय बंदरगाह अधिकारियों, तटरक्षक और IMD / INCOIS बुलेटिन देखें।',
  },

  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.dashboard': 'தகவல் பலகை',
    'nav.maps': 'நேரலை வரைபடம்',
    'nav.fishing': 'மீன்பிடி நுண்ணறிவு',
    'nav.marine_conditions': 'கடல் நிலைமைகள்',
    'nav.earth_observation': 'பூமி கண்காணிப்பு (செயற்கைக்கோள்)',
    'nav.navigation': 'புவிசார் & வழிகாட்டல்',
    'nav.safety': 'பேரிடர் & பாதுகாப்பு',
    'nav.operations': 'கடல்சார் செயல்பாடுகள்',
    'nav.ask': 'OCEANIS-ஐக் கேளுங்கள்',
    'nav.agents': 'முகவர்கள்',
    'nav.reports': 'அறிக்கைகள்',
    'nav.data_sources': 'தரவு மூலங்கள்',
    'nav.analytics': 'பகுப்பாய்வு',
    'nav.settings': 'அமைப்புகள்',
    'nav.change_loc': 'மாற்று',
    'nav.select_loc': 'இடத்தைத் தேர்ந்தெடுக்கவும்',
    'nav.sector_suffix': 'பிரிவு',
    'nav.offshore_sector': 'கடலோரப் பகுதி',
    'nav.inland_sector': 'உள்நாட்டுப் பகுதி',
    'nav.loc_not_selected': 'இடம் தேர்ந்தெடுக்கப்படவில்லை',

    // Dashboard & Overview
    'dash.title': 'கடல்சார் தகவல் பலகை',
    'dash.subtitle': 'ஒருங்கிணைந்த கடல்சார் முடிவு நுண்ணறிவு மற்றும் செயல்பாட்டு டெலிமெட்ரி',
    'dash.live_map_title': 'நேரலை கடல் நுண்ணறிவு வரைபடம்',
    'dash.safety_status': 'பாதுகாப்பு நிலை',
    'dash.trusted_sources': 'நம்பகமான நிறுவன தரவு மூலங்கள்',
    'dash.system_status': 'கணினி நிலை',
    'dash.active_advisories': 'செயல்பாட்டு எச்சரிக்கைகள்',
    'dash.fishing_suitability': 'மீன்பிடி பொருத்தம்',
    'dash.satellite_eo': 'செயற்கைக்கோள் பூமி கண்காணிப்பு',
    'dash.decision_summary': 'செயல்பாட்டு முடிவு நுண்ணறிவு',
    'dash.what_if': 'கடல்சார் வாட்-இஃப் உருவகப்படுத்துதல்',

    // Ask OCEANIS
    'ask.title': 'OCEANIS-ஐக் கேளுங்கள்',
    'ask.subtitle': 'சிறப்பு முகவர்களால் உருவாக்கப்பட்ட இயற்கை மொழி மற்றும் குரல் கடல் நுண்ணறிவு.',
    'ask.input_placeholder': 'கடல்சார் கேள்விகளைக் கேளுங்கள் (தமிழ், English, Hindi...)',
    'ask.btn_analyze': 'ஆய்வு செய்',
    'ask.btn_consulting': 'ஆலோசிக்கிறது...',
    'ask.voice_btn': 'குரல்',
    'ask.voice_listening': 'கேட்கிறது...',
    'ask.voice_banner': 'கேட்கிறது... உங்கள் கடல் கேள்வியை இயல்பாகப் பேசுங்கள்',
    'ask.read_aloud': 'வாசித்துக்காட்டு',
    'ask.stop_voice': 'குரலை நிறுத்து',
    'ask.why_title': 'இந்த முடிவு ஏன்?',
    'ask.why_sub': 'சுற்றுச்சூழல் மற்றும் ஒழுங்குமுறை காரணிகளின் பல கள சான்றுகள்',
    'ask.agents_consulted': 'ஆலோசிக்கப்பட்ட முகவர்கள்',
    'ask.agents_sub': 'சான்றுகளுடன் கூடிய ஒருங்கிணைப்பு',
    'ask.evidence_title': 'கட்டமைக்கப்பட்ட சான்றுகள்',
    'ask.evidence_sub': 'உண்மையான டெலிமெட்ரி',
    'ask.follow_up_label': 'தொடர் கேள்விகள்:',
    'ask.recent_turns': 'சமீபத்திய உரையாடல்கள்',
    'ask.confidence': 'நம்பகத்தன்மை',
    'ask.telemetry': 'டெலிமெட்ரி',

    // Statuses & Badges
    'status.recommended': 'பரிந்துரைக்கப்படுகிறது',
    'status.caution': 'எச்சரிக்கை',
    'status.not_recommended': 'பரிந்துரைக்கப்படவில்லை',
    'status.insufficient_evidence': 'போதுமான சான்றுகள் இல்லை',
    'status.fresh': 'புதியது (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'கிடைக்கவில்லை',
    'status.operational': 'செயல்பாட்டில் உள்ளது',
    'status.synchronized': 'ஒத்திசைக்கப்பட்டது',
    'status.clear': 'பயணத்திற்கு ஏற்றது',
    'status.warning': 'எச்சரிக்கை',
    'status.alert': 'அலர்ட்',

    // Disclaimer
    'disclaimer.text': 'முடிவு ஆதரவு அமைப்பு — கடல் பாதுகாப்புக்கான உத்தரவாதம் அல்ல. கடலுக்குச் செல்வதற்கு முன் அதிகாரப்பூர்வ உள்ளூர் துறைமுக அதிகாரிகள், கடலோர காவல்படை மற்றும் IMD / INCOIS புல்லட்டின்களைப் பார்க்கவும்.',
  },

  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.maps': 'ಲೈವ್ ನಕ್ಷೆ',
    'nav.fishing': 'ಮೀನುಗಾರಿಕೆ ಮಾಹಿತಿ',
    'nav.marine_conditions': 'ಸಾಗರ ಪರಿಸ್ಥಿತಿಗಳು',
    'nav.earth_observation': 'ಭೂ ವೀಕ್ಷಣೆ (ಉಪಗ್ರಹ)',
    'nav.navigation': 'ಭೂ-ಪ್ರಾದೇಶಿಕ & ಸಂಚಾರ',
    'nav.safety': 'ವಿಪತ್ತು & ಸುರಕ್ಷತೆ',
    'nav.operations': 'ಸಾಗರ ಕಾರ್ಯಾಚರಣೆಗಳು',
    'nav.ask': 'OCEANIS ಅನ್ನು ಕೇಳಿ',
    'nav.agents': 'ಏಜೆಂಟರು',
    'nav.reports': 'ವರದಿಗಳು',
    'nav.data_sources': 'ಡೇಟಾ ಮೂಲಗಳು',
    'nav.analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.change_loc': 'ಬದಲಾಯಿಸಿ',
    'nav.select_loc': 'ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
    'nav.sector_suffix': 'ವಲಯ',
    'nav.offshore_sector': 'ಆಫ್‌ಶೋರ್ ವಲಯ',
    'nav.inland_sector': 'ಒಳನಾಡು ವಲಯ',
    'nav.loc_not_selected': 'ಸ್ಥಳ ಆಯ್ಕೆಯಾಗಿಲ್ಲ',
    'dash.title': 'ಸಾಗರ ಗುಪ್ತಚರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'dash.subtitle': 'ಏಕೀಕೃತ ಸಾಗರ ನಿರ್ಧಾರ ಗುಪ್ತಚರ ಮತ್ತು ಕಾರ್ಯಾಚರಣೆಯ ಟೆಲಿಮೆಟ್ರಿ',
    'dash.live_map_title': 'ಲೈವ್ ಸಾಗರ ಗುಪ್ತಚರ ನಕ್ಷೆ',
    'dash.safety_status': 'ಸುರಕ್ಷತಾ ಸ್ಥಿತಿ',
    'dash.trusted_sources': 'ವಿಶ್ವಾಸಾರ್ಹ ಸಂಸ್ಥೆಯ ಡೇಟಾ ಮೂಲಗಳು',
    'dash.system_status': 'ವ್ಯವಸ್ಥೆಯ ಸ್ಥಿತಿ',
    'dash.active_advisories': 'ಕಾರ್ಯಾಚರಣೆಯ ಸಲಹೆಗಳು',
    'dash.fishing_suitability': 'ಮೀನುಗಾರಿಕೆ ಸೂಕ್ತತೆ',
    'dash.satellite_eo': 'ಉಪಗ್ರಹ ಭೂ ವೀಕ್ಷಣೆ',
    'dash.decision_summary': 'ಕಾರ್ಯಾಚರಣೆಯ ನಿರ್ಧಾರ ಗುಪ್ತಚರ',
    'dash.what_if': 'ವಾಟ್-ಇಫ್ ಸಾಗರ ಸಿಮ್ಯುಲೇಶನ್',
    'ask.title': 'OCEANIS ಅನ್ನು ಕೇಳಿ',
    'ask.subtitle': 'ನೈಸರ್ಗಿಕ ಭಾಷೆ ಮತ್ತು ಧ್ವನಿ ಸಾಗರ ಗುಪ್ತಚರ ಮಾಹಿತಿ.',
    'ask.input_placeholder': 'ಯಾವುದೇ ಸಾಗರ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ (ಕನ್ನಡ, English, Hindi...)',
    'ask.btn_analyze': 'ವಿಶ್ಲೇಷಿಸಿ',
    'ask.btn_consulting': 'ಸಮಾಲೋಚಿಸಲಾಗುತ್ತಿದೆ...',
    'ask.voice_btn': 'ಧ್ವನಿ',
    'ask.voice_listening': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...',
    'ask.voice_banner': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ... ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಮಾತನಾಡಿ',
    'ask.read_aloud': 'ಓದಿ ಹೇಳಿ',
    'ask.stop_voice': 'ಧ್ವನಿ ನಿಲ್ಲಿಸಿ',
    'ask.why_title': 'ಈ ನಿರ್ಧಾರ ಏಕೆ?',
    'ask.why_sub': 'ಪರಿಸರ ಮತ್ತು ನಿಯಂತ್ರಕ ಅಂಶಗಳ ಪುರಾವೆ',
    'ask.agents_consulted': 'ಸಂಪರ್ಕಿಸಿದ ಏಜೆಂಟರು',
    'ask.agents_sub': 'ಬಹು-ಏಜೆಂಟ್ ಸಮನ್ವಯ',
    'ask.evidence_title': 'ರಚನಾತ್ಮಕ ಪುರಾವೆಗಳು',
    'ask.evidence_sub': 'ನೈಜ ಟೆಲಿಮೆಟ್ರಿ ಮಾಹಿತಿ',
    'ask.follow_up_label': 'ಮುಂದಿನ ಪ್ರಶ್ನೆಗಳು:',
    'ask.recent_turns': 'ಇತ್ತೀಚಿನ ಸಂಭಾಷಣೆಗಳು',
    'ask.confidence': 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
    'ask.telemetry': 'ಟೆಲಿಮೆಟ್ರಿ',
    'status.recommended': 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    'status.caution': 'ಎಚ್ಚರಿಕೆ',
    'status.not_recommended': 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿಲ್ಲ',
    'status.insufficient_evidence': 'ಸಾಕಷ್ಟು ಪುರಾವೆಗಳಿಲ್ಲ',
    'status.fresh': 'ತಾಜಾ (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'ಲಭ್ಯವಿಲ್ಲ',
    'status.operational': 'ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ',
    'status.synchronized': 'ಸಿಂಕ್ರೊನೈಸ್ ಮಾಡಲಾಗಿದೆ',
    'status.clear': 'ಪ್ರಯಾಣಕ್ಕೆ ಸೂಕ್ತ',
    'status.warning': 'ಎಚ್ಚರಿಕೆ',
    'status.alert': 'ಅಲರ್ಟ್',
    'disclaimer.text': 'ನಿರ್ಧಾರ ಬೆಂಬಲ ವ್ಯವಸ್ಥೆ — ಸಾಗರ ಸುರಕ್ಷತೆಯ ಖಾತರಿಯಲ್ಲ. ಸಮುದ್ರಕ್ಕೆ ಹೋಗುವ ಮುನ್ನ ಅಧಿಕೃತ ಬಂದರು ಅಧಿಕಾರಿಗಳು, ಕೋಸ್ಟ್ ಗಾರ್ಡ್ ಮತ್ತು IMD / INCOIS ಬುಲೆಟಿನ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
  },

  ml: {
    'nav.home': 'ഹോം',
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.maps': 'തത്സമയ ഭൂപടം',
    'nav.fishing': 'മത്സ്യബന്ധന വിവരങ്ങൾ',
    'nav.marine_conditions': 'സമുദ്രാവസ്ഥ',
    'nav.earth_observation': 'ഭൗമ നിരീക്ഷണം (ഉപഗ്രഹം)',
    'nav.navigation': 'ഭൂമിശാസ്ത്ര & നാവിഗേഷൻ',
    'nav.safety': 'ദുരന്ത & സുരക്ഷ',
    'nav.operations': 'സമുദ്ര പ്രവർത്തനങ്ങൾ',
    'nav.ask': 'OCEANIS-നോട് ചോദിക്കൂ',
    'nav.agents': 'ഏജന്റുകൾ',
    'nav.reports': 'റിപ്പോർട്ടുകൾ',
    'nav.data_sources': 'ഡാറ്റാ ഉറവിടങ്ങൾ',
    'nav.analytics': 'അനലിറ്റിക്സ്',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.change_loc': 'മാറ്റുക',
    'nav.select_loc': 'സ്ഥലം തിരഞ്ഞെടുക്കുക',
    'nav.sector_suffix': 'മേഖല',
    'nav.offshore_sector': 'തീരദേശ മേഖല',
    'nav.inland_sector': 'ഉൾനാടൻ മേഖല',
    'nav.loc_not_selected': 'സ്ഥലം തിരഞ്ഞെടുത്തിട്ടില്ല',
    'dash.title': 'സമുദ്ര ഇന്റലിജൻസ് ഡാഷ്‌ബോർഡ്',
    'dash.subtitle': 'സംയോജിത മൾട്ടി-ഏജന്റ് സമുദ്ര തീരുമാന വിവരങ്ങൾ',
    'dash.live_map_title': 'തത്സമയ സമുദ്ര ഭൂപടം',
    'dash.safety_status': 'സുരക്ഷാ നില',
    'dash.trusted_sources': 'വിശ്വാസയോഗ്യമായ ഡാറ്റാ ഉറവിടങ്ങൾ',
    'dash.system_status': 'സിസ്റ്റം നില',
    'dash.active_advisories': 'പ്രവർത്തന മുന്നറിയിപ്പുകൾ',
    'dash.fishing_suitability': 'മത്സ്യബന്ധന അനുയോജ്യത',
    'dash.satellite_eo': 'ഉപഗ്രഹ ഭൗമ നിരീക്ഷണം',
    'dash.decision_summary': 'തീരുമാന വിവരങ്ങൾ',
    'dash.what_if': 'വാട്ട്-ഇഫ് സിമുലേഷൻ',
    'ask.title': 'OCEANIS-നോട് ചോദിക്കൂ',
    'ask.subtitle': 'പ്രത്യേക ഏജന്റുകൾ നൽകുന്ന സ്വാഭാവിക ഭാഷാ സമുദ്ര വിവരങ്ങൾ.',
    'ask.input_placeholder': 'സമുദ്ര സംബന്ധിയായ ചോദ്യങ്ങൾ ചോദിക്കുക (മലയാളം, English, Hindi...)',
    'ask.btn_analyze': 'വിശകലനം ചെയ്യുക',
    'ask.btn_consulting': 'ഏജന്റുകളോട് ചോദിക്കുന്നു...',
    'ask.voice_btn': 'വോയ്‌സ്',
    'ask.voice_listening': 'കേൾക്കുന്നു...',
    'ask.voice_banner': 'കേൾക്കുന്നു... നിങ്ങളുടെ ചോദ്യം സംസാരിക്കുക',
    'ask.read_aloud': 'വായിച്ചു കേൾപ്പിക്കുക',
    'ask.stop_voice': 'നിർത്തുക',
    'ask.why_title': 'എന്തുകൊണ്ട് ഈ തീരുമാനം?',
    'ask.why_sub': 'പാരിസ്ഥിതിക തെളിവുകൾ',
    'ask.agents_consulted': 'പങ്കെടുത്ത ഏജന്റുകൾ',
    'ask.agents_sub': 'വിവര ശേഖരണം',
    'ask.evidence_title': 'തെളിവുകൾ & ഉറവിടങ്ങൾ',
    'ask.evidence_sub': 'യഥാർത്ഥ ടെലിമെട്രി ഡാറ്റ',
    'ask.follow_up_label': 'തുടർ ചോദ്യങ്ങൾ:',
    'ask.recent_turns': 'സംഭാഷണങ്ങൾ',
    'ask.confidence': 'വിശ്വാസ്യത',
    'ask.telemetry': 'ടെലിമെട്രി',
    'status.recommended': 'ശുപാർശ ചെയ്യുന്നു',
    'status.caution': 'ജാഗ്രത',
    'status.not_recommended': 'ശുപാർശ ചെയ്യുന്നില്ല',
    'status.insufficient_evidence': 'മതിയായ തെളിവുകളില്ല',
    'status.fresh': 'പുതിയത് (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'ലഭ്യമല്ല',
    'status.operational': 'പ്രവർത്തനക്ഷമം',
    'status.synchronized': 'സിൻക്രൊണൈസ്ഡ്',
    'status.clear': 'യാത്രയ്ക്ക് അനുയോജ്യം',
    'status.warning': 'മുന്നറിയിപ്പ്',
    'status.alert': 'അലർട്ട്',
    'disclaimer.text': 'തീരുമാന പിന്തുണാ സംവിധാനം — സമുദ്ര സുരക്ഷ ഉറപ്പല്ല. കടലിലേക്ക് പോകുന്നതിന് മുൻപ് ഔദ്യോഗിക പോർട്ട് അധികൃതരുടെയും കോസ്റ്റ് ഗാർഡിന്റെയും IMD / INCOIS വിവരങ്ങൾ പരിശോധിക്കുക.',
  },

  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.maps': 'थेट नकाशा',
    'nav.fishing': 'मासेमारी माहिती',
    'nav.marine_conditions': 'सागरी परिस्थिती',
    'nav.earth_observation': 'पृथ्वी निरीक्षण (उपग्रह)',
    'nav.navigation': 'भू-स्थानिक आणि नेव्हिगेशन',
    'nav.safety': 'आपत्ती आणि सुरक्षा',
    'nav.operations': 'सागरी ऑपरेशन्स',
    'nav.ask': 'OCEANIS ला विचारा',
    'nav.agents': 'एजंट्स',
    'nav.reports': 'अहवाल',
    'nav.data_sources': 'डेटा स्रोत',
    'nav.analytics': 'अॅनालिटिक्स',
    'nav.settings': 'सेटिंग्ज',
    'nav.change_loc': 'बदला',
    'nav.select_loc': 'स्थान निवडा',
    'nav.sector_suffix': 'सेक्टर',
    'nav.offshore_sector': 'ऑफशोर सेक्टर',
    'nav.inland_sector': 'अंतर्देशीय सेक्टर',
    'nav.loc_not_selected': 'स्थान निवडलेले नाही',
    'dash.title': 'सागरी माहिती डॅशबोर्ड',
    'dash.subtitle': 'एकात्मिक सागरी निर्णय माहिती आणि ऑपरेशनल टेलीमेट्री',
    'dash.live_map_title': 'थेट महासागर माहिती नकाशा',
    'dash.safety_status': 'सुरक्षा स्थिती',
    'dash.trusted_sources': 'विश्वासार्ह संस्थात्मक डेटा स्रोत',
    'dash.system_status': 'प्रणाली स्थिती',
    'dash.active_advisories': 'ऑपरेशनल सूचना',
    'dash.fishing_suitability': 'मासेमारी उपयुक्तता',
    'dash.satellite_eo': 'उपग्रह पृथ्वी निरीक्षण',
    'dash.decision_summary': 'ऑपरेशनल निर्णय माहिती',
    'dash.what_if': 'व्हॉट-इफ सागरी सिम्युलेशन',
    'ask.title': 'OCEANIS ला विचारा',
    'ask.subtitle': 'तज्ज्ञ डोमेन एजंट्सद्वारे विश्लेषित नैसर्गिक भाषा आणि व्हॉइस सागरी माहिती.',
    'ask.input_placeholder': 'सागरी प्रश्न विचारा (मराठी, English, Hindi...)',
    'ask.btn_analyze': 'विश्लेषण करा',
    'ask.btn_consulting': 'एजंट्सशी सल्लामसलत करत आहे...',
    'ask.voice_btn': 'व्हॉइस',
    'ask.voice_listening': 'ऐकत आहे...',
    'ask.voice_banner': 'ऐकत आहे... तुमचा प्रश्न स्पष्ट बोला',
    'ask.read_aloud': 'मोठ्याने वाचा',
    'ask.stop_voice': 'आवाज थांबवा',
    'ask.why_title': 'हा निर्णय का?',
    'ask.why_sub': 'पर्यावरणीय आणि नियामक घटकांचे पुरावे',
    'ask.agents_consulted': 'सल्ला घेतलेले एजंट्स',
    'ask.agents_sub': 'डेटा समन्वय',
    'ask.evidence_title': 'संरचित पुरावे आणि स्रोत',
    'ask.evidence_sub': 'वास्तविक टेलीमेट्री',
    'ask.follow_up_label': 'पुढील प्रश्न:',
    'ask.recent_turns': 'मागील संभाषणे',
    'ask.confidence': 'विश्वासार्हता',
    'ask.telemetry': 'टेलीमेट्री',
    'status.recommended': 'शिफारस केलेले',
    'status.caution': 'खबरदारी',
    'status.not_recommended': 'शिफारस केलेली नाही',
    'status.insufficient_evidence': 'अपुरा पुरावा',
    'status.fresh': 'ताजे (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'अनुपलब्ध',
    'status.operational': 'सक्रिय',
    'status.synchronized': 'सिंक्रोनाइझ्ड',
    'status.clear': 'प्रवासासाठी सुरक्षित',
    'status.warning': 'चेतावणी',
    'status.alert': 'अलर्ट',
    'disclaimer.text': 'निर्णय समर्थन प्रणाली — सागरी सुरक्षेची हमी नाही. समुद्रात जाण्यापूर्वी नेहमी स्थानिक बंदर अधिकारी, तटरक्षक दल आणि IMD / INCOIS बुलेटिन तपासा.',
  },

  bn: {
    'nav.home': 'হোম',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.maps': 'লাইভ মানচিত্র',
    'nav.fishing': 'মৎস্য শিকার তথ্য',
    'nav.marine_conditions': 'সামুদ্রিক অবস্থা',
    'nav.earth_observation': 'পৃথিবী পর্যবেক্ষণ (উপগ্রহ)',
    'nav.navigation': 'ভূ-स्थानিক এবং নেভিগেশন',
    'nav.safety': 'দুর্যোগ ও নিরাপত্তা',
    'nav.operations': 'সামুদ্রিক কার্যক্রম',
    'nav.ask': 'OCEANIS-কে জিজ্ঞাসা করুন',
    'nav.agents': 'এজেন্ট',
    'nav.reports': 'রিপোর্ট',
    'nav.data_sources': 'তথ্য সূত্র',
    'nav.analytics': 'অ্যানালিটিক্স',
    'nav.settings': 'সেটিংস',
    'nav.change_loc': 'পরিবর্তন',
    'nav.select_loc': 'স্থান নির্বাচন করুন',
    'nav.sector_suffix': 'সেক্টর',
    'nav.offshore_sector': 'অফশোর সেক্টর',
    'nav.inland_sector': 'অভ্যন্তরীণ সেক্টর',
    'nav.loc_not_selected': 'স্থান নির্বাচিত নয়',
    'dash.title': 'সামুদ্রিক গোয়েন্দা ড্যাশবোর্ড',
    'dash.subtitle': 'সমন্বিত সামুদ্রিক সিদ্ধান্ত গোয়েন্দা ও অপারেশনাল টেলিমেট্রি',
    'dash.live_map_title': 'লাইভ সমুদ্র মানচিত্র',
    'dash.safety_status': 'নিরাপত্তা স্থিতি',
    'dash.trusted_sources': 'বিশ্বস্ত প্রাতিষ্ঠানিক তথ্য সূত্র',
    'dash.system_status': 'সিস্টেম স্থিতি',
    'dash.active_advisories': 'অপারেশনাল সতর্কতা',
    'dash.fishing_suitability': 'মৎস্য শিকার উপযোগিতা',
    'dash.satellite_eo': 'উপগ্রহ পৃথিবী পর্যবেক্ষণ',
    'dash.decision_summary': 'সিদ্ধান্ত গোয়েন্দা তথ্য',
    'dash.what_if': 'হোয়াট-ইফ সামুদ্রিক সিমুলেশন',
    'ask.title': 'OCEANIS-কে জিজ্ঞাসা করুন',
    'ask.subtitle': 'বিশেষজ্ঞ এজেন্টদের দ্বারা সংশ্লেষিত প্রাকৃতিক ভাষা এবং ভয়েস তথ্য।',
    'ask.input_placeholder': 'যেকোনো সামুদ্রিক প্রশ্ন জিজ্ঞাসা করুন (বাংলা, English, Hindi...)',
    'ask.btn_analyze': 'বিশ্লেষণ করুন',
    'ask.btn_consulting': 'পরামর্শ করা হচ্ছে...',
    'ask.voice_btn': 'ভয়েস',
    'ask.voice_listening': 'শুনছি...',
    'ask.voice_banner': 'শুনছি... আপনার প্রশ্নটি স্পষ্টভাবে বলুন',
    'ask.read_aloud': 'পড়ে শোনান',
    'ask.stop_voice': 'ভয়েস বন্ধ করুন',
    'ask.why_title': 'এই সিদ্ধান্ত কেন?',
    'ask.why_sub': 'পরিবেশগত ও নিয়ন্ত্রক উপাত্ত',
    'ask.agents_consulted': 'পরামর্শকৃত এজেন্ট',
    'ask.agents_sub': 'তথ্য সমন্বয়',
    'ask.evidence_title': 'কাঠামোগত প্রমাণ ও উৎস',
    'ask.evidence_sub': 'বাস্তব টেলিমেট্রি তথ্য',
    'ask.follow_up_label': 'পরবর্তী প্রশ্ন:',
    'ask.recent_turns': 'সাম্প্রতিক কথোপকথন',
    'ask.confidence': 'আত্মবিশ্বাস',
    'ask.telemetry': 'টেলিমেট্রি',
    'status.recommended': 'সুপারিশকৃত',
    'status.caution': 'সতর্কতা',
    'status.not_recommended': 'সুপারিশকৃত নয়',
    'status.insufficient_evidence': 'অপর্যাপ্ত প্রমাণ',
    'status.fresh': 'তাজা (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'অনুপলব্ধ',
    'status.operational': 'সক্রিয়',
    'status.synchronized': 'সিঙ্ক্রোনাইজড',
    'status.clear': 'যাত্রার জন্য উপযুক্ত',
    'status.warning': 'সতর্কবার্তা',
    'status.alert': 'অ্যালার্ট',
    'disclaimer.text': 'সিদ্ধান্ত সহায়তা সিস্টেম — সামুদ্রিক নিরাপত্তার নিশ্চয়তা নয়। সমুদ্রে যাওয়ার আগে সর্বদা স্থানীয় বন্দর কর্তৃপক্ষ, কোস্ট গার্ড এবং IMD / INCOIS বুলেটিন দেখুন।',
  },

  gu: {
    'nav.home': 'હોમ',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.maps': 'લાઈવ નકશો',
    'nav.fishing': 'મત્સ્યપાલન માહિતી',
    'nav.marine_conditions': 'દરિયાઈ સ્થિતિ',
    'nav.earth_observation': 'પૃથ્વી અવલોકન (સેટેલાઇટ)',
    'nav.navigation': 'ભૂ-સ્થાનિક અને નેવિગેશન',
    'nav.safety': 'હોનારત અને સુરક્ષા',
    'nav.operations': 'દરિયાઈ કામગીરી',
    'nav.ask': 'OCEANIS ને પૂછો',
    'nav.agents': 'એજન્ટ્સ',
    'nav.reports': 'અહેવાલો',
    'nav.data_sources': 'ડેટા સ્ત્રોતો',
    'nav.analytics': 'એનાલિટિક્સ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.change_loc': 'બદલો',
    'nav.select_loc': 'સ્થળ પસંદ કરો',
    'nav.sector_suffix': 'સેક્ટર',
    'nav.offshore_sector': 'દરિયાકાંઠા ક્ષેત્ર',
    'nav.inland_sector': 'અંતર્દેશીય ક્ષેત્ર',
    'nav.loc_not_selected': 'સ્થળ પસંદ કરેલ નથી',
    'dash.title': 'સમુદ્રી ઇન્ટેલિજન્સ ડેશબોર્ડ',
    'dash.subtitle': 'સંકલિત દરિયાઈ નિર્ણય બુદ્ધિ અને ઓપરેશનલ ટેલિમેટ્રી',
    'dash.live_map_title': 'લાઈવ સમુદ્રી નકશો',
    'dash.safety_status': 'સુરક્ષા સ્થિતિ',
    'dash.trusted_sources': 'વિશ્વસનીય સંસ્થાકીય ડેટા સ્ત્રોતો',
    'dash.system_status': 'સિસ્ટમ સ્થિતિ',
    'dash.active_advisories': 'ઓપરેશનલ સલાહ',
    'dash.fishing_suitability': 'મત્સ્યપાલન અનુકૂળતા',
    'dash.satellite_eo': 'સેટેલાઇટ પૃથ્વી અવલોકન',
    'dash.decision_summary': 'ઓપરેશનલ નિર્ણય બુદ્ધિ',
    'dash.what_if': 'વૉટ-ઇફ દરિયાઈ સિમ્યુલેશન',
    'ask.title': 'OCEANIS ને પૂછો',
    'ask.subtitle': 'કુદરતી ભાષા અને અવાજ આધારિત દરિયાઈ માહિતી.',
    'ask.input_placeholder': 'દરિયાઈ પ્રશ્ન પૂછો (ગુજરાતી, English, Hindi...)',
    'ask.btn_analyze': 'વિશ્લેષણ કરો',
    'ask.btn_consulting': 'એજન્ટ્સનો સંપર્ક થઈ રહ્યો છે...',
    'ask.voice_btn': 'અવાજ',
    'ask.voice_listening': 'સાંભળી રહ્યું છે...',
    'ask.voice_banner': 'સાંભળી રહ્યું છે... તમારો પ્રશ્ન બોલો',
    'ask.read_aloud': 'વાંચી સંભળાવો',
    'ask.stop_voice': 'અવાજ બંધ કરો',
    'ask.why_title': 'આ નિર્ણય શા માટે?',
    'ask.why_sub': 'પર્યાવરણીય અને નિયમનકારી પરિબળોના પુરાવા',
    'ask.agents_consulted': 'સંપર્ક કરેલ એજન્ટ્સ',
    'ask.agents_sub': 'ડેટા સંકલન',
    'ask.evidence_title': 'માળખાગત પુરાવા અને સ્ત્રોતો',
    'ask.evidence_sub': 'વાસ્તવિક ટેલિમેટ્રી ડેટા',
    'ask.follow_up_label': 'આગળના પ્રશ્નો:',
    'ask.recent_turns': 'તાજેતરની વાતચીતો',
    'ask.confidence': 'વિશ્વાસ',
    'ask.telemetry': 'ટેલિમેટ્રી',
    'status.recommended': 'ભલામણ કરેલ',
    'status.caution': 'સાવધાની',
    'status.not_recommended': 'ભલામણ કરેલ નથી',
    'status.insufficient_evidence': 'અપૂરતા પુરાવા',
    'status.fresh': 'તાજું (Fresh)',
    'status.aging': 'AGING',
    'status.stale': 'STALE',
    'status.unavailable': 'અનુપલબ્ધ',
    'status.operational': 'કાર્યરત',
    'status.synchronized': 'સમન્વયિત',
    'status.clear': 'મુસાફરી માટે સુરક્ષિત',
    'status.warning': 'ચેતવણી',
    'status.alert': 'એલર્ટ',
    'disclaimer.text': 'નિર્ણય સહાયક પ્રણાલી — દરિયાઈ સલામતીની ખાતરી નથી. દરિયામાં જતા પહેલા હંમેશા સત્તાવાર સ્થાનિક બંદર અધિકારીઓ, કોસ્ટ ગાર્ડ અને IMD / INCOIS બુલેટિન તપાસો.',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, defaultVal?: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'oceanis_global_language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as SupportedLanguage;
      if (saved && TRANSLATIONS[saved]) {
        return saved;
      }
    } catch {
      // ignore
    }
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang);
      try {
        localStorage.setItem(STORAGE_KEY, lang);
      } catch {
        // ignore
      }
    }
  };

  const t = (key: string, defaultVal?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return defaultVal || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
