from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class DisasterSafetyQuery(BaseModel):
    """
    Input query payload for Disaster & Safety Intelligence Agent.
    """
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Latitude in decimal degrees (-90.0 to 90.0)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Longitude in decimal degrees (-180.0 to 180.0)")
    radius_km: float = Field(50.0, ge=1.0, le=1000.0, description="Search radius in kilometers (default 50.0 km)")
    target_datetime: Optional[str] = Field(None, description="Optional target date or ISO 8601 timestamp")


class SafetyEvidenceItem(BaseModel):
    """
    Standardized traceable safety evidence item with provenance and regulatory attributes.
    """
    factor: str = Field(..., description="Safety factor identifier (e.g. active_alert, hazard_containment, cyclone_proximity, telemetry_coverage)")
    title: Optional[str] = Field(None, description="Title or descriptor of the hazard/alert")
    entity_type: str = Field("HAZARD", description="OFFICIAL_ALERT, HAZARD_ZONE, CYCLONE_TRACK, TELEMETRY_COVERAGE, SAFE_PORT")
    severity: str = Field("NORMAL", description="NORMAL, INFO, CAUTION, WARNING, CRITICAL, UNKNOWN")
    source: str = Field("INCOIS / IMD", description="Data authority or provider (e.g. INCOIS, IMD, JTWC)")
    source_category: str = Field("OFFICIAL", description="OFFICIAL, MODEL/FORECAST, DEMO/TEST, UNKNOWN")
    data_type: str = Field("OFFICIAL_WARNING", description="OFFICIAL_WARNING, OBSERVED_HAZARD, FORECAST_HAZARD, AI_ASSESSMENT, SPATIAL_INFRASTRUCTURE")
    observed_at: Optional[str] = Field(None, description="ISO timestamp of observation/issuance")
    effective_from: Optional[str] = Field(None, description="ISO timestamp when threat becomes active")
    effective_until: Optional[str] = Field(None, description="ISO timestamp when threat expires")
    distance_km: Optional[float] = Field(None, description="Distance from requested coordinates in kilometers")
    spatial_relationship: str = Field("PROXIMITY", description="CONTAINS, INSIDE, PROXIMITY, OUTSIDE, NEAR_BOUNDARY")
    confidence: float = Field(1.0, ge=0.0, le=1.0, description="Deterministic confidence score between 0.0 and 1.0")
    freshness: str = Field("FRESH", description="Freshness evaluation: FRESH, AGING, STALE, UNAVAILABLE, EXPIRED")
    notes: Optional[str] = Field(None, description="Diagnostic safety context note")


class AlertSummary(BaseModel):
    """
    Structured summary of an active or nearby marine warning/advisory.
    """
    id: Optional[int] = None
    alert_id: str
    title: str
    alert_type: str
    severity: str
    status: str = "ACTIVE"
    description: Optional[str] = None
    source: str = "INCOIS"
    source_category: str = "OFFICIAL"
    issued_at: Optional[str] = None
    effective_from: Optional[str] = None
    effective_until: Optional[str] = None
    distance_km: Optional[float] = None
    freshness: str = "FRESH"


class HazardSummary(BaseModel):
    """
    Structured summary of a spatial hazard zone (e.g. storm surge, reef, high wave risk).
    """
    id: Optional[int] = None
    name: str
    hazard_type: str
    severity: str
    description: Optional[str] = None
    source: str = "INCOIS"
    source_category: str = "OFFICIAL"
    distance_km: Optional[float] = None
    contains_point: bool = False
    freshness: str = "FRESH"


class CycloneSummary(BaseModel):
    """
    Structured summary of an active or forecast tropical cyclone system.
    """
    id: Optional[int] = None
    cyclone_id: str
    name: str
    basin: str = "NORTH_INDIAN_OCEAN"
    classification: str
    latitude: float
    longitude: float
    wind_speed_kmh: Optional[float] = None
    pressure_hpa: Optional[float] = None
    movement_direction_deg: Optional[float] = None
    movement_speed_kmh: Optional[float] = None
    observed_at: Optional[str] = None
    forecast_time: Optional[str] = None
    distance_km: Optional[float] = None
    data_type: str = "OBSERVED"
    freshness: str = "FRESH"


class SafePortSummary(BaseModel):
    """
    Structured summary of the nearest designated safe harbor or maritime refuge.
    """
    id: Optional[int] = None
    name: str
    port_type: Optional[str] = None
    distance_km: Optional[float] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    country: Optional[str] = None
    state: Optional[str] = None


class DisasterSafetyAssessmentResponse(BaseModel):
    """
    Structured response generated by the Disaster & Safety Intelligence Agent.
    """
    agent: str = Field("disaster_safety", description="Name of the domain agent")
    location: Dict[str, float] = Field(..., description="Target coordinate latitude and longitude")
    safety_status: str = Field(..., description="Deterministic safety state: CLEAR, CAUTION, WARNING, CRITICAL, BLOCKED, INSUFFICIENT_DATA")
    risk_level: str = Field("LOW", description="Overall risk level: LOW, MODERATE, HIGH, EXTREME, UNKNOWN")
    hazards: List[HazardSummary] = Field(default_factory=list, description="Containing and nearby spatial hazard zones")
    alerts: List[AlertSummary] = Field(default_factory=list, description="Active official marine warnings and advisories")
    cyclones: List[CycloneSummary] = Field(default_factory=list, description="Active tropical cyclones and storm tracks")
    nearest_safe_port: Optional[SafePortSummary] = Field(None, description="Nearest coastal port or harbor of safe refuge")
    distance_to_hazards: List[Dict[str, Any]] = Field(default_factory=list, description="Summary list of hazard distances")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Deterministic confidence rating between 0.0 and 1.0")
    data_freshness: str = Field("FRESH", description="Freshness status of underlying disaster telemetry")
    evidence: List[SafetyEvidenceItem] = Field(default_factory=list, description="Traceable safety evidence provenance items")
    warnings: List[str] = Field(default_factory=list, description="Active danger warnings, caution notices, or data caveats")
    recommendation: str = Field(..., description="Actionable safety guidance and operational directives")
    explanation: str = Field(..., description="Evidence-based deterministic reasoning narrative")
    generated_at: datetime = Field(..., description="UTC timestamp of response generation")

    model_config = ConfigDict(from_attributes=True)
