from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class MarineConditionsQuery(BaseModel):
    """
    Input query payload for Marine Conditions Intelligence Agent.
    """
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Latitude in decimal degrees (-90.0 to 90.0)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Longitude in decimal degrees (-180.0 to 180.0)")
    target_datetime: Optional[str] = Field(None, description="Optional target date or ISO 8601 timestamp")


class MarineConditionsEvidenceItem(BaseModel):
    """
    Standardized traceable evidence item for marine physical observations and forecasts.
    """
    factor: str = Field(..., description="Oceanographic attribute name (e.g. wave_height, swell_height, current_velocity, sst)")
    value: Optional[Any] = Field(None, description="Recorded metric value")
    unit: Optional[str] = Field(None, description="Measurement unit (m, s, deg, km/h, °C)")
    source: str = Field(..., description="Data provider or model source")
    observed_at: Optional[str] = Field(None, description="ISO timestamp of observation/validity")
    retrieved_at: Optional[str] = Field(None, description="ISO timestamp when telemetry was ingested")
    data_type: str = Field("OBSERVATION", description="OBSERVATION, FORECAST, OFFICIAL_WARNING, AI_ASSESSMENT")
    quality: str = Field("GOOD", description="Quality flag: GOOD, MODERATE, SUSPECT, UNKNOWN")
    freshness: str = Field("FRESH", description="Freshness evaluation: FRESH, AGING, STALE, EXPIRED, UNKNOWN")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Deterministic confidence score between 0.0 and 1.0")
    severity: str = Field("NORMAL", description="Factor severity: NORMAL, MODERATE, ROUGH, SEVERE, UNKNOWN")
    notes: Optional[str] = Field(None, description="Diagnostic observation note")


class MarineConditionsSummary(BaseModel):
    """
    Raw oceanographic and sea state telemetry metrics.
    """
    wave_height_m: Optional[float] = None
    wave_direction_deg: Optional[float] = None
    wave_period_s: Optional[float] = None
    swell_wave_height_m: Optional[float] = None
    swell_wave_direction_deg: Optional[float] = None
    swell_wave_period_s: Optional[float] = None
    wind_wave_height_m: Optional[float] = None
    wind_wave_direction_deg: Optional[float] = None
    wind_wave_period_s: Optional[float] = None
    ocean_current_velocity_kmh: Optional[float] = None
    ocean_current_direction_deg: Optional[float] = None
    sea_surface_temperature_c: Optional[float] = None
    observed_at: Optional[str] = None
    source: Optional[str] = None
    data_type: Optional[str] = None
    quality_flag: Optional[str] = None


class MarineConditionsAssessmentResponse(BaseModel):
    """
    Structured response generated by the Marine Conditions Intelligence Agent.
    """
    agent: str = Field("marine_conditions", description="Name of the domain agent")
    location: Dict[str, float] = Field(..., description="Target coordinate latitude and longitude")
    conditions: Dict[str, Any] = Field(default_factory=dict, description="Detailed marine conditions summary")
    sea_state: str = Field(..., description="Overall sea state classification: NORMAL, MODERATE, ROUGH, SEVERE, INSUFFICIENT_DATA")
    risk_level: str = Field(..., description="Assessed physical risk level: LOW, MODERATE, HIGH, CRITICAL, UNKNOWN")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Deterministic confidence rating between 0.0 and 1.0")
    data_freshness: str = Field("FRESH", description="Freshness status of underlying telemetry")
    evidence: List[MarineConditionsEvidenceItem] = Field(default_factory=list, description="Traceable provenance evidence items")
    warnings: List[str] = Field(default_factory=list, description="List of physical oceanographic hazard alerts")
    recommendation: str = Field(..., description="Actionable marine condition recommendation")
    explanation: str = Field(..., description="Evidence-based reasoning narrative")
    generated_at: datetime = Field(..., description="UTC timestamp of response generation")

    model_config = ConfigDict(from_attributes=True)
